<?php echo $this->getChildHtml('items_before'); ?>
<div id="checkout-review-table-wrapper">
    <table class="order-products-table summaryTable" id="checkout-review-table" width="100%">

        <tbody>
        <?php foreach($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item)?>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
<script type="text/javascript">
//<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
//]]>
</script>
