<?php

$designer_name = $this->getData('designer_name');
$dashboard_url = Mage::getUrl('productupload/designer/guide', array('_secure' => true));;
?>

<div>
    <span>Xin chào <?php echo $designer_name?></span>
    <br/>
    <span>
        Bạn đã đăng ký thành công chương trình Designer của Soloyo.
    </span>
    <br/>
    <span>Hãy truy cập </span> <a href="<?php echo $dashboard_url ?>"> tài khoản của bạn </a> để đọc hướng dẫn và bắt đầu kiếm tiền cùng Soloyo ngay hôm nay.</span>
</div>
