<?php

$campaign_id = $this->getRequest()->getParam('id');
if(!$campaign_id){
    $campaign_id = '3';
}
$campaign =  Mage::getModel('campaign/campaign')->load($campaign_id);
$banner = Mage::helper('campaign')->getUrlImageCampaign(). $campaign->getImageShare();
$name = $campaign->getName();
$url = $campaign->getUrl();
?>
<meta property="og:title" content="<?php echo $name; ?>">
<meta property="og:image" content="<?php echo $banner; ?>">
<meta property="fb:app_id" content="279145496124660">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="628">
<meta property="og:url" content="<?php echo $url; ?>">
<meta property="og:type" content="article" >
<meta property="og:site_name" content="Soloyo" >
<meta property="og:description" content="<?php echo $name ?>" >
<link rel="canonical" href="<?php echo $url ?>">



