<div style="width: 80%">
    <h1>Soloyo xin thông báo đến các Designer một vài cập nhật mới nhất:</h1>

    <table style="width: 100%">
        <tr>
            <td style="padding: 10px 10px ;color: #2d2d2d;">
                <span>1. Đã có tính năng Mockup Template cho Designer: Bạn có thể tải các Mockup dạng đơn giản (không đẹp), đồng thời cũng có thể chia sẻ các Mockup của các dòng điện thoại mà bạn đang có đẹp hơn mẫu của hệ thống.</span>
                <br/>
                <span>
            Trong thời gian tới Soloyo sẽ tiếp tục thiết kế để cho ra các Mockup đẹp hơn giúp các bạn thiết kế được nhanh hơn.
                </span>
                <br/>
                <span>
                Số lượng mockup đã update còn hạn chế. Bạn nào muốn sử dụng mockup này và muốn update thêm cho dòng điện thoại mình đang thiết kế. Có thể yêu cầu qua email này.
                </span>
            </td>
        </tr>
        <tr>
            <td style="padding: 10px 10px">
                <img style="width: 100%; border: solid 1px #f2f3f5" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). DS.'email'.DS.'mockup_template.png';  ?>" alt="mockup_template">
            </td>

        </tr>
        <tr>
            <td style="padding: 10px 10px">
                <img style="width: 100%; border: solid 1px #f2f3f5" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). DS.'email'.DS.'share_mockup.png';  ?>" alt="share_mockup">
            </td>
        </tr>
        <tr>
            <td style="padding: 10px 10px;color: #2d2d2d;">
                <span>2. Thêm tính năng Link Builder : Một link gồm tất cả các thiết kế của các bạn. Các bạn có thể sử dụng link này để giới thiệu các thiết kế của mình đến mọi người nếu muốn.</span>
            </td>

        </tr>
        <tr>
            <td style="padding: 10px 10px;color: #2d2d2d;">
                <img style="width: 100%; border: solid 1px #f2f3f5" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). DS.'email'.DS.'link_builder.png' ?>" alt="link_builder">
            </td>
        </tr>
        <tr>
            <td style="padding: 10px 10px;color: #2d2d2d;">
                3. Chương trình Sale Off lớn nhất năm sẽ diễn ra vào ngày 1/1/2019, các bạn hãy nhanh tay thiết kế để tăng số lượng đơn hàng của mình trong lần Sale này nhé.
            </td>
        </tr>
    </table>

</div>