<div class="row">
<?php
    $this->setDateInput('d',
        '<div class="dob-day col-xs-4">
             <input type="text" placeholder="DD" id="' . $this->getFieldId('day') . '" name="' . $this->getFieldName('day') . '" value="' . $this->getDay() . '" title="' . $this->__('Day') . '" class="fm_box fw t1 validate-custom" ' . $this->getFieldParams() . ' />
         </div>'
    );

    $this->setDateInput('m',
        '<div class="dob-month col-xs-4">
             <input type="text" placeholder="MM" id="' . $this->getFieldId('month') . '" name="' . $this->getFieldName('month') . '" value="' . $this->getMonth()  . '" title="' . $this->__('Month')  . '" class="fm_box fw t1 validate-custom" ' . $this->getFieldParams()  . ' />
         </div>'
    );

    $this->setDateInput('y',
        '<div class="dob-year col-xs-4">
             <input type="text" placeholder="YYYY" id="' . $this->getFieldId('year') . '" name="' . $this->getFieldName('year') . '" value="' . $this->getYear()  . '" title="' . $this->__('Year')  . '" class="fm_box fw t1 validate-custom" ' . $this->getFieldParams()  . ' />
         </div>'
    );

    echo $this->getSortedDateInputs() 
?>
    <div class="dob-full" style="display:none;">
        <input type="hidden" id="<?php echo $this->getFieldId('dob')?>" name="<?php echo $this->getFieldName('dob')?>" />
    </div>

    <div class="validation-advice" style="display:none;"></div>
</div>
<script type="text/javascript">
//<![CDATA[
    var customer_dob = new Varien.DOB('.customer-dob', <?php echo $this->isRequired() ? 'true' : 'false' ?>, '<?php echo $this->getDateFormat() ?>');
//]]>
</script>
