<div class="<?php echo $this->getContainerClassName() ?>">

    <div class="cRow">
        <div class="label-row col-md-4">
            <span><?php echo $this->__('Họ và tên') ?></span>
        </div>
        <div class="col-md-8">
            <input type="text" id="<?php echo $this->getFieldId('firstname') ?>"
                   name="<?php echo $this->getFieldName('firstname') ?>"
                   value="<?php echo $this->htmlEscape($this->getObject()->getFirstname()) ?>"
                   title="<?php echo $this->__('First name') ?>"
                   placeholder="Nguyễn Văn A"
                   class="onestepcheckout-input required-entry" <?php echo $this->getFieldParams() ?> maxlength="32"/>
        </div>
    </div>

</div>
