<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()){?>
<?php
$login_url	= $this->getUrl('*/*/login', array('_secure'=>(!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on')));
$http_mode	= (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on');
if($http_mode)
	$login_url	= str_replace('http:', 'https:', $login_url);  
?>
<div id="check_login_form" class="mfp-hide zoom-anim-dialog formMain">
	<div class="popUpMain">
		<div class="popupInner">
			<div class="form-head"><img src="<?php echo $this->getSkinUrl('images/lock-icon.png'); ?>" alt=""></div>
			<form method="post" id="checkoutLoginForm" action="<?php echo $login_url ?>">
				<div class="boxcontent form_fields">
					<div class="fieldRow">
						<input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="fm_box fw input-text required-entry validate-email" placeholder="<?php echo $this->__('Email Address') ?>" title="<?php echo $this->__('Email Address') ?>" size="30" />
					</div>
					<div class="fieldRow">
						<input type="password" name="login[password]" class="fm_box fw input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" placeholder="<?php echo $this->__('Password') ?>" size="30" />
					</div>
				</div>
				<div class="fieldRow">
					<button type="submit" class="btn btn-fluid button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
					<span class="please-wait" id="login-please-wait" style="display:none;">
						<img src="<?php echo $this->getSkinUrl('images/onestepcheckout/opc-ajax-loader_onestepcheckout.gif') ?>" class="v-middle" alt=""/>
					</span>
				</div>
				<a href="javascript:void(0);" class="f-left onestepcheckout_forgotlink" onclick='open_forgot();'><?php echo $this->__('Forgot Your Password?') ?></a>
			</form>
		</div>
	</div>
</div>
    <script type="text/javascript">
    //<![CDATA[
        var checkoutLoginForm = new VarienForm('checkoutLoginForm', true);
    //]]>
    </script>
</div>
<?php }?>