<div style="font-family: vietnam_font;color: #2d2d2d;justify-content: center">
    <h1 style="font-size: 32px">Hướng dẫn thiết kế ốp lưng cùng Soloyo</h1>

    <div class="row" style="margin-top: 40px;">
        <h3>Bước 1: Lấy kích thước của dòng điện thoại cần thiết kế</h3>
        <div class="col-md-4">
            <span>Chọn mục <b>"Kích thước cho thiết kế"</b></span>
            <br/>
            <span>
            Lựa chọn hãng điện thoại và dòng điện thoại muốn thiết kế
        </span>
            <br/>
            <span>
            Bấm vào nút <b>Tìm ngay</b>
        </span>
            <br/>
        </div>
        <div class="col-md-8">
            <img src="<?php echo $this->getSkinUrl('images/kich-thuoc-cho-thiet-ke.png'); ?>"
                 alt="kich-thuoc-cho-thiet-ke" style="width: 90%">
        </div>
    </div>

    <div class="row" style="margin-top: 20px">
        <h3>Bước 2: Thiết kế</h3>
        <div class="col-md-12">
            <span>Với mỗi thiết kế bạn cần làm 2 ảnh: ảnh cho in ấn và ảnh mockup cho sản phẩm.</span>
            <br/>
            <div style="margin-top: 10px">
            <span>Các lưu ý cho ảnh dùng để in ấn: </span>
            <ul >
                <li style="list-style-type:disc;margin-left: 20px;">Phải sử dụng định dạng màu CMYK.</li>
                <li style="list-style-type:disc;margin-left: 20px;">Nên sử dụng ảnh vector để bản in được đẹp nhất.</li>
                <li style="list-style-type:disc;margin-left: 20px;">Độ phân giải cho thiết kế là : 300dpi</li>
                <li style="list-style-type:disc;margin-left: 20px;">File phải được lưu dưới định dạng pdf</li>

            </ul>
            </div>
            <div style="margin-top: 10px">
            <span>Lưu ý cho ảnh mockup : Kích thước ảnh phải là 500 x 500 pixel hoặc 1000 x 1000 pixel</span>
            </div>
            <div style="margin-top: 10px">
            <span>Mẹo làm một mẫu cho nhiều loại điện thoại:</span>
            <ul>
                <li style="list-style-type:disc;margin-left: 20px;">
                    Hãy tạo ra 1 file gốc với tất cả các layer
                </li>

                <li style="list-style-type:disc;margin-left: 20px;">
                    Sau đó tạo ra các file cho các dòng điện thoại khác nhau với kích thước lấy ở bước 1.
                </li>

                <li style="list-style-type:disc;margin-left: 20px;">
                    Kéo các layer từ file gốc sang các file của dòng điện thoại và thực hiện điều chỉnh cho phù hợp với
                    vị trí camera. Điều chỉnh hệ màu và xuất ra định dạnh pdf.
                </li>
            </ul>
            </div>
        </div>
    </div>

    <div style="margin-top: 20px">
        <h3>Bước 3: Tải thiết kế lên hệ thống để bán</h3>
        <div class="row">
            <div class="col-md-4">
                <span>Chọn <b>Các thiết kế của tôi</b> </span>
                <br/>
                <span>Chọn <b>Thiết kế ngay</b> hoặc <b>Thêm thiết kế mới</b> để bắt đầu tải thiết kế lên</span>
                <br/>

            </div>
            <div class="col-md-8">
                <img src=" <?php echo $this->getSkinUrl('images/tai-thiet-ke-1.png'); ?> " alt="tai-thiet-ke"
                     style="width: 90%">
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <span>Chọn hãng điện thoại và dòng điện thoại</span>
                <br/>
                <span>
            Nhập tên chủ đề và tên mẫu thiết kế.
        </span>
                <br/>
                <span>
            Chọn ảnh mockup và ảnh để in ấn.
        </span>
                <br/>
                <span>
            Chọn <b>Save</b> để tải lên.
        </span>
            </div>
            <div class="col-md-8">
                <img src=" <?php echo $this->getSkinUrl('images/tai-thiet-ke-2.png'); ?> " alt="tai-thiet-ke"
                     style="width: 90%">
            </div>
        </div>
    </div>
</div>