<?php
$designer = Mage::helper('productupload')->getDesigner();
$status = $designer->getStatus();
?>
<?php if ($status == 1): ?>
    <div >

        <div >
            <ul id="designer-tab-ul">
                <?php $_links = $this->getLinks(); ?>
                <?php $_index = 1; ?>
                <?php $_count = count($_links); ?>
                <?php foreach ($_links as $_link): ?>
                    <?php $_last = ($_index++ >= $_count); ?>
                    <?php if ($this->isActive($_link)): ?>
                        <li class="designer-tab-current<?php echo ($_last ? ' designer-tab-last' : '') ?>"><strong><?php echo $_link->getLabel() ?></strong></li>
                    <?php else: ?>
                        <li<?php echo ($_last ? ' class="designer-tab-last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>