<?php

$designer_id = $this->getCurrentDesignerId();

$mockup_url = $this->getUrl('*/*/mockup',array('_secure' => true));

?>

<h1>Chia sẻ Mockup của bạn với mọi người</h1>
<div>
    <div class="button-container col-md-12">
        <button class="btn-save-new-mockup-disable" id="btn-save-new-mockup">Chia sẻ</button>
        <button id="btn-cancel-mockup">Cancel</button>
    </div>

    <div >
        <form action="<?php echo Mage::getUrl('productupload/designer/createNewMockup', array('_secure' => true)); ?>" method="post" id="form-new-mockup"
              class="scaffold-form"
              enctype="multipart/form-data">

            <input type="hidden" name="form_key"
                   value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>

            <input type="hidden" name="designer_id" value="<?php echo $designer_id ?>"/>



            <div class="row new-design-row">
                <h5>Mockup cho</h5>
                <div class="custom-select-container col-md-6">

                    <input type="hidden" name="brand_id" id="brand-mobile-input"
                           value=""/>
                    <div class="custom-select" id="brand-mobile" onclick="select_brand()">
                        <span type="text" class="custom-select-content">Lựa chọn một hãng điện thoại</span>
                        <i class="material-icons md-24 ">arrow_drop_down</i>
                    </div>
                    <div class="custom-select-option box-shadow-class" id="brand-mobile-value"
                         style="display: none">

                    </div>
                </div>

                <div class="custom-select-container col-md-6">

                    <input type="hidden" name="model_id" id="model-mobile-input"
                           value=""/>
                    <div class="custom-select" id="model-mobile" onclick="select_mobile()">
                        <span type="text" class="custom-select-content">Lựa chọn một dòng điện thoại</span>
                        <i class="material-icons md-24 ">arrow_drop_down</i>
                    </div>
                    <div class="custom-select-option box-shadow-class" id="model-mobile-value"
                         style="display: none">

                    </div>
                </div>

            </div>



            <div class="row new-design-row">
                <div class="col-md-6">
                    <h5>Ảnh mockup </h5>
                    <div>

                        <input style="margin-top: 10px;" type="file" name="mockup_file" id="mockup_file-design">
                    </div>

                </div>

            </div>


        </form>
    </div>

</div>

<script>

    var brand_model_url = '<?php echo Mage::getUrl('brandmodel/index/brand_models', array('_secure' => true)); ?>';
    var mockup_url = '<?php echo $mockup_url; ?>';
</script>




